#config.yaml
hyperparameters:
  dataset_path: '~/datasets'
  cuda: False 
  epochs: 5
  batch_size: 100
  learning_rate: 1e-4
  x_dim: 784
  hidden_dim: 400
  latent_dim: 20
  channels: 1
  x_image_size: 28
  y_image_size: 28
  seed: 1234
  
  
